language: node_js
cache: yarn

# update yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

deploy:
  provider: script
  script: npx lerna publish -y from-git
  skip_cleanup: true
  on:
    tags: true
    branch: master

