language: node_js
cache: yarn
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
deploy:
  provider: script
  script: yarn deploy
  skip_cleanup: true
  on:
    branch: master

env:
  global:
    secure: Cj78E6jmjHrfwbCe/5BDYmGLvLReJVE7FTxw86Ipe7jLVp5F3hhKDY0kniyVXBPYazAckKCMC6EMcJfyw74CBpC1e3qlGWl8TiMV/zOryK14zHLguv1aCSw5k0IWt+KBxCuI0mABd8x0n8xKYCDuRULE4JdEqB+tAXG21KW08lc2XUgaOvAmLeh/8OMWKER5v6g1dU7qvpVLXEqWh0+sDYV8aQiILGb9PjPcN/1YeW2AmUtILbnw3N4FEWPoeMxCXSaU3xH5lhYMSU7JcpW9APJJzP/AWarGb1STUiEG0AbcmnxqGcbGB8JB3dscQmbYmRe5zJwGgrBSbgZ6aAc3tbjoGrUtJOBCHFkz0xfnZPdZZ4uEgGmghMNrtLySsrueL0mpH9LhWiU/d8uXh2mUVMbTgQgQFX02Q/4ck19gC7g5bYFticPNufCauevnmGMfT1hC8cEuU9HowT3v44IJI3+1xkeztJc4Fc9iIewC1cvoZS5w7HWopEcoAya6Xr2ZRycjkQ0pSMFCAViCLRZ8qn1iu0VIm+nyIMUB080QJ9Puc3G7W/YHKAhAy+k8zwfnKM6RXdjGvW0OyMBBnvo/v5ntU4rtXdaZwRBn5WcmssiX5k6Y05hrJQO4yTH7IATEe0pIbA7ZDmaZPEITwsCYUL7WgSFP+vtE/HnMQY+kdgE=
