name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
    - name: Cache node_modules and Firebase emulator
      uses: actions/cache@master
      with:
        path: |
          node_modules
          */*/node_modules
          /home/runner/.cache/firebase/emulators
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
    - name: Install dependencies
      run: yarn install
    - name: Set release id
      run: sed -i "s|NO RELEASE ID SPECIFIED|$GITHUB_SHA|g" ./packages/firebase-functions/src/release.ts
    - name: Run tests
      run: yarn test
    - name: Deploy to Firebase
      if: matrix.node-version == '13.x' && startsWith(github.ref, 'refs/tags/v')
      run: yarn deploy
      env:
        CI: true
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    - name: Slack notification after deployment success
      if: matrix.node-version == '13.x' && startsWith(github.ref, 'refs/tags/v') && success()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: GitHub Actions 
        SLACK_CHANNEL: build
        SLACK_AVATAR: repository
      with:
        args: 'Deployed <https://github.com/hoepel-app/hoepel-app/actions/runs/${{ github.run_id }}|`${{ github.ref }}`> to Firebase.'
      uses: Ilshidur/action-slack@master
    - name: Slack notification on build failure
      if: failure() && !startsWith(github.ref, 'refs/heads/dependabot/npm_and_yarn/')
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: GitHub Actions 
        SLACK_CHANNEL: build
        SLACK_AVATAR: repository
      uses: Ilshidur/action-slack@master
      with:
        args: 'Build for <https://github.com/hoepel-app/hoepel-app/actions/runs/${{ github.run_id }}|`${{ github.ref }}`> failed :crying_cat_face:'
